### ISSUE TITLE
from bindsnet.analysis.plotting import (     plot_input,     plot_spikes,     plot_conv2d_weights,     plot_voltages, )

### ISSUE THREAD

**Issue by tehreemnaqvi** [khengyeww/sym-STDP#3]
Hi,
I want to plot input spikes, conv2d_weights, voltages.
But I am confused how from bindsnet.analysis.plotting works?
Can you please how can I visualize all these?
Thanks

**Comment by khengyeww** [comment]
I assume this is more a question to BindsNET rather than this repo.

You can run this [sample (which uses conv layer)](https://github.com/BindsNET/bindsnet/blob/master/examples/mnist/conv_mnist.py) provided by BindsNET with `--plot` flag. It uses the functions you mentioned and visualize them.

**Comment by tehreemnaqvi** [comment]
Got it.
Thank you

**Comment by tehreemnaqvi** [comment]
Hi, Below is my code.I am trying to show the plot but couldn't do this.
What's the problem here?
Can you please help?
Thanks
        # Optionally plot various simulation information.
        if plot:
            image = batch["image"].view( 28, 28 )

            inpt = inputs["X"].view( time, 784 ).sum( 0 ).view( 28, 28 )
            weights1 = conv_conn.w
            _spikes = {
                "X": spikes["X"].get( "s" ).view( time, -1 ),
                "Y": spikes["Y"].get( "s" ).view( time, -1 ),
            }
            _voltages = {"Y": voltages["Y"].get( "v" ).view( time, -1 )}

            inpt_axes, inpt_ims = plot_input(
                image, inpt, label=label, axes=inpt_axes, ims=inpt_ims
            )
            spike_ims, spike_axes = plot_spikes( _spikes, ims=spike_ims, axes=spike_axes )
            weights1_im = plot_conv2d_weights( weights1, im=weights1_im )
            voltage_ims, voltage_axes = plot_voltages(
                _voltages, ims=voltage_ims, axes=voltage_axes
            )

            plt.ioff()
            plt.show()
